### PR TITLE
Updated probability code, magic bait, expanded window and tackle display

### PR DESCRIPTION
**Pull request by Sandman534**
- Updated the probability code to exclude some things that I should not have added in. Mainly Garbage.
- Added in logic to look for all valid fish if you are using Magic Bait
- With this, I changed the way the window is sized and it can now render multiple columns. This includes a new option to choose how many fish to show per column. Had to do this because with magic bait the available fish window can be quite long, especially with mods.
- Added a new feature where you can see your current bait and tackle. This has a new set of options below Fish Probability and you can anchor the window wherever you want, or have it attach to the probability window
- Also un-commented the logging functionality and put them to display only if the game is in debug mode

### CODE REVIEW

**Comment by Sandman534** [comment]
Note that the new options I added into translation are google translated... I dont know any other languages.

**Comment by Sandman534** [comment]
I also did try to add Furniture in, but there are a lot of conditions surrounding furniture, and since its all catch it once and no more... I think excluding furniture as a whole is the best idea. I'm sure there are ways to make it work, but I dont think the effort is worth the payoff...

**Comment by Hackswell** [comment]
Can you please pull the develop16 branch and ensure I didn't break the merge?  Thanks.

**Comment by Hackswell** [comment]
Also, please add config option information to FeaturesAndConfigs.md, please.

**Pull request merged**
